### ISSUE TITLE
NodeJS 8+ : default ECDH curve changed and is not accepted by website

### ISSUE THREAD

**Issue by laedit** [nicofrand/cozy-konnector-materielnet#3] opened 2018-02-13 20:56 UTC
Thanks for this connector!

But since a few days, I've got only login failed instead of the usual synchronization on my cozy cloud instance.
Since I don't have access to the production logs I don't know if it's the same issue but when I have tried to reproduce the issue on my fork i've got some SSL related issues:

>write EPROTO 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\\ssl\\s23_clnt.c:802

After some searching, it appears that the use of `tls.DEFAULT_ECDH_CURVE = 'auto';` fix it.

Do you also have the issue?

**Comment by nicofrand** [comment] 2018-02-13 21:02
No, I don't have this issue. Would you mind telling me which version of node you are using ? Maybe something changed regarding this TLS configuration..


If that's the case, I'll take a look and maybe take your fix, thanks !


Le 13 févr. 2018 21:56, Jérémie Bertrand <notifications@github.com> a écrit :

Thanks for this connector!

But since a few days, I've got only login failed instead of the usual synchronization on my cozy cloud instance.
Since I don't have access to the production logs I don't know if it's the same issue but when I have tried to reproduce the issue on my fork i've got some SSL related issues:

write EPROTO 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\ssl\s23_clnt.c:802

After some searching, it appears that the use of tls.DEFAULT_ECDH_CURVE = 'auto'; fix it.

Do you also have the issue?

**Comment by nicofrand** [comment] 2018-02-13 21:03
No, I don't have this issue. Would you mind telling me which version of node you are using ? Maybe something changed regarding this TLS configuration..


If that's the case, I'll take a look and maybe take your fix, thanks !




Le 13 févr. 2018 21:56, Jérémie Bertrand <notifications@github.com> a écrit :

Thanks for this connector!

But since a few days, I've got only login failed instead of the usual synchronization on my cozy cloud instance.
Since I don't have access to the production logs I don't know if it's the same issue but when I have tried to reproduce the issue on my fork i've got some SSL related issues:

write EPROTO 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\ssl\s23_clnt.c:802

After some searching, it appears that the use of tls.DEFAULT_ECDH_CURVE = 'auto'; fix it.

Do you also have the issue?

**Comment by laedit** [comment] 2018-02-14 04:12
I have tested it with node v8.8.1 and v9.5.0, but I don't know which version is used in the mycozy.cloud instance.

**Comment by nicofrand** [comment] 2018-02-14 07:53
Fixed by https://github.com/nicofrand/cozy-konnector-materielnet/commit/87ee3063c7b87076c30eba43e61684874d302909

Thanks for the debugging!

**Comment by laedit** [comment] 2018-02-14 07:54
Thanks a lot for your quick response! :)

**Closed by nicofrand** 2018-02-14 07:53 UTC
